### 1.
Install the transformers and torch libraries using pip, then write a Python script that prints the version numbers of both libraries to confirm successful installation.

In [1]:
!pip install transformers torch -q


[notice] A new release of pip is available: 26.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import transformers
import torch

In [3]:
transformers.__version__

'5.13.0'

In [4]:
torch.__version__

'2.13.0+cpu'

### 3.
Use the Hugging Face pipeline to perform sentiment analysis on three recent Zomato or Swiggy app reviews (copy-paste the review text) and print the predicted sentiment for each.

In [5]:
from transformers import pipeline

In [7]:
sentiment_pipeline = pipeline('sentiment-analysis')

[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.


Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [8]:
reviews = [
    'The delivery was incredibly fast and the food was hot!',
    'Worst biryani I have ever had, completely tasteless.',
    'Decent portion size but a bit overpriced for what you get.'
]

In [10]:
for review in reviews:
    result = sentiment_pipeline(review)[0]
    print(f"Review: '{review}'\nPredicted Sentiment: {result['label']} (Score: {result['score']})\n")

Review: 'The delivery was incredibly fast and the food was hot!'
Predicted Sentiment: POSITIVE (Score: 0.9996817111968994)

Review: 'Worst biryani I have ever had, completely tasteless.'
Predicted Sentiment: NEGATIVE (Score: 0.9997696280479431)

Review: 'Decent portion size but a bit overpriced for what you get.'
Predicted Sentiment: NEGATIVE (Score: 0.9893428087234497)



### 5.
Use ChatGPT or Copilot to generate a simple Python function that demonstrates the attention mechanism with three short sentences as input, and explain in your own words (2-3 lines) what the attention scores mean in your output.<br><br><em><strong>Hint:</strong> Ask the AI tool to 'show a basic attention calculation example in Python.'</em>

**My Prompt to ChatGPT:**
> Show a basic attention calculation example in Python demonstrating the attention mechanism with three short sentences as input. Do not include comments in the code.

**Explanation of Attention Scores:**
The attention scores represent how much "focus" or "importance" each word gives to every other word in the sequence. A higher score means the model learned that those two words are strongly related to each other's context within the sentence.

In [11]:
import numpy as np

def simple_attention(query, keys, values):
    scores = np.dot(query, keys.T)
    weights = np.exp(scores) / np.sum(np.exp(scores), axis=-1, keepdims=True)
    output = np.dot(weights, values)
    return output, weights

In [12]:
sentences = ['I love food', 'Food is good', 'I am hungry']
# Dummy embeddings for the 3 sentences (size=4)
embeddings = np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.2, 0.3, 0.4, 0.5],
    [0.9, 0.8, 0.7, 0.6]
])

In [13]:
query = embeddings 
keys = embeddings
values = embeddings

output, attention_weights = simple_attention(query, keys, values)

print('Attention Weights Matrix:\n', np.round(attention_weights, 4))

Attention Weights Matrix:
 [[0.278  0.3072 0.4147]
 [0.2517 0.2896 0.4587]
 [0.1369 0.1848 0.6782]]
